services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: coffee_point_crm_admin
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      USE_CLOUD_SQL_PROXY: false
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JWT_POINT_SECRET_KEY: ${JWT_POINT_SECRET_KEY}
      JWT_ADMIN_SECRET_KEY: ${JWT_ADMIN_SECRET_KEY}
      PRIVATE_KEY_ID: ${PRIVATE_KEY_ID}
      PRIVATE_KEY: ${PRIVATE_KEY}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
